name: Testing React Client Application

on:
  push:
    paths:
      - "client/**"
    branches: [master, development]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "14.x"

      - name: Install dependencies
        working-directory: client
        run: npm install

      - name: Run all tests
        working-directory: client
        run: npm test
